apiVersion: v1
kind: ConfigMap
metadata:
  name: actiondash-config
  namespace: zechcodes
  labels:
    app: actiondash
data:
  AUTH_REDIRECT_BASE_URL: "https://actiondash.zech.sh"
  SESSION_COOKIE_DOMAIN: ".zech.sh"
